### ISSUE TITLE
Function names

### ISSUE THREAD

**Issue by msroji** [Sadat154/Programming-Challenges#1]
https://github.com/Sadat154/Programming-Challenges/blob/865f083b148826fe25399e859926b8872376bf76/Brampton%20Manor%20Academy/Programming%20Challenges/Programming%20Challenges%201/1%20-%20Rod%20Conversions.py#L4

Do not be tempted to use abbreviations when choosing names. Always try to use the most concise but descriptive names possible.

https://peps.python.org/pep-0008/#prescriptive-naming-conventions

**Comment by Sadat154** [comment]
Function names have been adjusted to be more concise and descriptive, Thanks!
