### ISSUE TITLE
f string padding

### ISSUE THREAD

**Issue by ecoppen** [Sadat154/Programming-Challenges#4]
https://github.com/Sadat154/Programming-Challenges/blob/865f083b148826fe25399e859926b8872376bf76/Brampton%20Manor%20Academy/Programming%20Challenges/2%20-%20Richters/main.py#L13-L15

You shouldn't be typing out the spacing! f strings have you covered: https://saralgyaan.com/posts/f-string-in-python-usage-guide/#How_to_add_space_padding_in_Python_f-strings?

For example:
`print(f"{richterList[i]:<5}{Joules(richterList[i]):<30}{TNT(richterList[i]):<30}") `

**Comment by Sadat154** [comment]
Is there a way to use f string padding for line 13 where there are no variables being used ive tried: print(f"Richter {:>30} Joules {:>30} TNT {:<30}

**Comment by ecoppen** [comment]
Yes there is! Put the string inside the `{}` brackets but in the alternative speech marks to whatever you opened the f string with. So `f"` would mean you use `'` and vice versa.

`print(f"{'Richter':>30}{'Joules':>30}{'TNT':<30}`

**Comment by Sadat154** [comment]
Thanks a lot sir, I have now fixed these issues.
